<script setup lang="ts">
import { computed } from 'vue'
import {
  Award,
  BadgeAlert,
  BadgeCheck,
  BadgeDollarSign,
  Ban,
  Bot,
  Box,
  Brain,
  Calendar,
  Check,
  Circle,
  CircleAlert,
  CircleCheck,
  CircleDollarSign,
  CircleOff,
  CirclePlus,
  CircleX,
  ClipboardList,
  Clock,
  Cloud,
  Compass,
  Crown,
  Disc3,
  Download,
  Eye,
  FilePenLine,
  FileText,
  FlaskConical,
  FolderOpen,
  Gift,
  Hand,
  Handshake,
  HardDrive,
  Info,
  KeyRound,
  Laptop,
  Lightbulb,
  Lock,
  LockKeyhole,
  Map,
  Medal,
  Megaphone,
  MessageCircle,
  MessageSquareText,
  Monitor,
  Package,
  Pencil,
  Plug,
  Rainbow,
  RefreshCw,
  Rocket,
  Scale,
  ScrollText,
  Search,
  Send,
  Settings,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TrainFront,
  TriangleAlert,
  Trophy,
  UserCheck,
  Video,
  Wrench,
  Zap,
} from '@lucide/vue'

const props = defineProps<{
  name: string
  label?: string
}>()

const icons = {
  award: Award,
  'badge-alert': BadgeAlert,
  'badge-check': BadgeCheck,
  'badge-dollar': BadgeDollarSign,
  ban: Ban,
  bot: Bot,
  box: Box,
  brain: Brain,
  calendar: Calendar,
  check: Check,
  circle: Circle,
  'circle-alert': CircleAlert,
  'circle-check': CircleCheck,
  'circle-dollar': CircleDollarSign,
  'circle-off': CircleOff,
  'circle-plus': CirclePlus,
  'circle-x': CircleX,
  clipboard: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  compass: Compass,
  crown: Crown,
  disc: Disc3,
  download: Download,
  eye: Eye,
  'file-pen': FilePenLine,
  file: FileText,
  flask: FlaskConical,
  folder: FolderOpen,
  gift: Gift,
  hand: Hand,
  handshake: Handshake,
  drive: HardDrive,
  info: Info,
  key: KeyRound,
  laptop: Laptop,
  lightbulb: Lightbulb,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  map: Map,
  medal: Medal,
  megaphone: Megaphone,
  message: MessageCircle,
  'message-text': MessageSquareText,
  monitor: Monitor,
  package: Package,
  pencil: Pencil,
  plug: Plug,
  rainbow: Rainbow,
  refresh: RefreshCw,
  rocket: Rocket,
  scale: Scale,
  scroll: ScrollText,
  search: Search,
  send: Send,
  settings: Settings,
  shield: ShieldCheck,
  smartphone: Smartphone,
  sparkles: Sparkles,
  star: Star,
  target: Target,
  train: TrainFront,
  warning: TriangleAlert,
  trophy: Trophy,
  'user-check': UserCheck,
  video: Video,
  wrench: Wrench,
  zap: Zap,
}

type IconName = keyof typeof icons

const iconComponent = computed(() => icons[props.name as IconName] ?? Circle)
</script>

<template>
  <component
    :is="iconComponent"
    class="doc-icon"
    aria-hidden="true"
  />
  <span v-if="label" class="sr-only">{{ label }}</span>
</template>
